title:            Drake's Brewhouse North
description:      A chronicle of my forray into DIY home improvement.
url:              http://dev.drakesbrewhouse.com

owner:
  name:           Dennis Rogers
  avatar:         avatar.jpg
  bio:            "I am a web developer and tech professional, mostly not making things worse."
  email:          dennis@drogers.net
  
paginate: 5

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]